= Usage
:doctype: book
:description: Usage for makemkvcon
:keywords: kotlin multiplatform, makemkv
:icons: font
:toc:
:toc-title: Contents
:toclevels: 10

link:../README.adoc[BACK]

== Synopsis

----
makemkvcon [options] Command Parameters
----

=== General options:

==== –messages=file

Output all messages to file. Following special file names are recognized:
-stdout - stdout
-stderr - stderr
-null - disable output
Default is stdout

==== –progress=file

Output all progress messages to file. The same special file names as in –messages are recognized with additional value "-same" to output to the same file as messages. Naturally –progress should follow –messages in this case. Default is no output.

==== –debug[=file]

Enables debug messages and optionally changes the location of debug file. Default: program preferences.

==== –directio=true/false

Enables or disables direct disc access. Default: program preferences.

==== –noscan

Don't access any media during disc scan and do not check for media insertion and removal. Helpful when other applications already accessing discs in other drives.

==== –cache=size

Specifies size of read cache in megabytes used by MakeMKV. By default program uses huge amount of memory. About 128 MB is recommended for streaming and backup, 512MB for DVD conversion and 1024MB for Blu-ray conversion.

=== Streaming options:

==== –upnp=true/false

Enable or disable UPNP streaming. Default: program preferences.

==== –bindip=address string

Specify IP address to bind. Default: None, UPNP server binds to the first available address and web server listens on all available addresses.

==== –bindport=port

Specify web server port to bind. Default: 51000.

=== Backup options:

==== –decrypt

Decrypt stream files during backup. Default: no decryption.

Conversion options:

==== –minlength=seconds

Specify minimum title length. Default: program preferences.

=== Automation options.

==== -r , –robot

Enables automation mode. Program will output more information in a format that is easier to parse. All output is line-based and output is flushed on line end. All strings are quoted, all control characters and quotes are backlash-escaped. If you automate this program it is highly recommended to use this option. Some options make reference to apdefs.h file that can be found in MakeMKV open-source package, included with version for Linux. These values will not change in future versions.

== Message formats

=== Message output

MSG:messageType,argsCount,localizedText,formattedString,args...

messageType - unique message code, should be used to identify particular string in language-neutral way.
argsCount - number of parameters
localizedText - raw message string suitable for output
formattedString - format string used for message. This string is localized and subject to change, unlike message code.
args - parameter for message

==== Message Types

===== Critical Error

[cols="1,1"]
|===
|*Code*
|*Meaning*

|1003
|ERR_READ_FILE

|1004
|ERR_WRITE_FILE

|2003
|ERR_AACS_FAIL

|2004
|ERR_BD_PLUS_FAIL

|5010
|ERR_RPC_ZONE
|===

===== Analysis And Titles
[cols="1,1"]
|===
|*Code*
|*Meaning*

|1005
|INFO_MAKEMKVCON

|1011
|INFO_LIBREDRIVE

|3001
|INFO_SCANNING

|3007
|INFO_DIRECT_ACCESS

|3025
|INFO_TITLE_SKIPPED

|3028
|INFO_TITLE_SKIPPED_TIME

|3307
|INFO_TITLE_ADDED

|5011
|INFO_OPERATION_COMPLETED

|5053
|INFO_MAIN_TITLE

|5085
|INFO_HASH_LOADED
|===

===== Status And Process Updates
[cols="1,1"]
|===
|*Code*
|*Meaning*

|4001
|PROG_START

|4002
|PROG_FINISH

|4003
|PROG_FAIL

|5014
|INFO_SPEED

|5038
|INFO_TIME_REMAIN
|===

=== Current and total progress title

PRGC:code,id,name
PRGT:code,id,name

code - unique message code
id - operation sub-id
name - name string

==== Progress Codes

[cols="1,1"]
|===
|*Code*
|*Meaning*

|3103
|ProgProcessingTitles

|3400
|ProgProcessingClips

|3401
|ProgProcessingPlaylists

|3402
|ProgDecrypting

|3404
|ProgOpeningDisc

|3406
|ProgProcessingBdPlus

|5018
|ProgScanningDevices
|===


=== Progress bar values for current and total progress

PRGV:current,total,max

current - current progress value
total - total progress value
max - maximum possible value for a progress bar, constant

=== Drive scan messages

DRV:index,visible,enabled,flags,drive name,disc name

index - drive index
visible - set to 1 if drive is present
enabled - set to 1 if drive is accessible
flags - media flags
drive name - drive name string
disc name - disc name string

==== Media Flags

[cols="1,1"]
|===
|*Code*
|*Meaning*

|0
| Empty

|1
|DVD inserted

|12
|Blu Ray Disc inserted
|===

=== Disc information output messages

TCOUT:count

count - titles count

=== Disc, title and stream information

CINFO:fieldId,typeIndicator,value
TINFO:fieldId,typeIndicator,value
SINFO:fieldId,typeIndicator,value

id - attribute id, see AP_ItemAttributeId in apdefs.h
code - message code if attribute value is a constant string
value - attribute value

==== Type Indicators

[cols="1,1"]
|===
|*Code*
|*Meaning*

|0
|String

|1
|Int

|2
|Long

|3
|Double

|4
|Boolean

|5
|ConstString

|10
|Binary

|6119
|Block_Sourceinformation

|6120
|Block_Titleinformation

|6121
|Block_Trackinformation

|6201
|MediaType_Video

|6202
|MediaType_Audio

|6203
|MediaType_Subtitles

|5088
|FormatFlag
|===

==== Disk Info Fields

[cols="1,1"]
|===
|*Code*
|*Meaning*

|1
|MediaTypeName

|2
|TitleName

|28
|LanguageCode

|29
|LanguageName

|30
|Information

|31
|HtmlHeader

|32
|VolumeName

|33
|VolumeId

|===

==== Track Info Fields

[cols="1,1"]
|===
|*Code*
|*Meaning*

|2
|TitleName

|8
|ChaptersCount

|9
|Duration

|10
|SizeStr

|11
|SizeLong

|16
|MplsName

|25
|SegmentCount

|26
|SegmentMap

|27
|OutputFileName

|28
|LanguageCode

|29
|LanguageName

|30
|Information

|31
|HtmlHeader

|33
|TitleId

|===

==== Stream Info Fields

[cols="1,1"]
|===
|*Code*
|*Meaning*

|1
|StreamType

|5
|CodecId

|6
|CodecShort

|7
|CodecLong

|19
|VideoResolution

|20
|VideoAspect

|21
|VideoFrameRate

|22
|BitDepth

|28
|LanguageCode

|29
|LanguageName

|30
|StreamInfo

|31
|HtmlHeader

|33
|StreamFlags

|38
|MetadataKey

|42
|ConversionType

|===

== Examples:

=== Copy all titles from first disc and save as MKV files:

----
makemkvcon mkv disc:0 all c:\folder
----

=== List all available drives

----
makemkvcon -r –cache=1 info disc:9999
----

=== Backup first disc decrypting all video files in automation mode with progress output

----
makemkvcon backup –decrypt –cache=16 –noscan -r –progress=-same disc:0 c:\folder
----

=== Start streaming server with all output suppressed on a specific address and port

----
makemvcon stream –upnp=1 –cache=128 –bindip=192.168.1.102 –bindport=51000 –messages=-none
----
